name: Bump Dependencies

on:
  repository_dispatch:
    types: [bump-dependencies]

jobs:
  bump-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
      with:
        egress-policy: audit

    - uses: spinnaker/bumpdeps@e80ad47c2a38b2c0709ab0ee9b916a263af05b6d # master
      with:
        ref: ${{ github.event.client_payload.ref }}
        baseBranch: ${{ github.event.client_payload.branch }}
        key: orcaVersion
        repositories: kayenta
        mavenRepositoryUrl: https://repo.maven.apache.org/maven2
        groupId: io.spinnaker.orca
        artifactId: orca-bom
      env:
        GITHUB_OAUTH: ${{ secrets.SPINNAKER_GITHUB_TOKEN }}
